/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.hms.view;

import br.com.hms.model.mPessoa;
import br.com.hms.view.GuiCadastroFuncionario;
import java.awt.Frame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Daniel
 */
public class GuiPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public GuiPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpAreaDeTrabalho = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlCadFunc = new javax.swing.JLabel();
        jlCadPaci = new javax.swing.JLabel();
        jlCadEstru = new javax.swing.JLabel();
        jlCadMedi = new javax.swing.JLabel();
        jlPesq = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpAreaDeTrabalho.setBackground(new java.awt.Color(214, 231, 187));
        jdpAreaDeTrabalho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jdpAreaDeTrabalho.setDesktopManager(null);

        jPanel1.setBackground(new java.awt.Color(214, 231, 187));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(172, 231, 187), new java.awt.Color(214, 231, 187), null, null));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hms/images/logo.png"))); // NOI18N

        jlCadFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hms/images/BOTAO01.PNG"))); // NOI18N
        jlCadFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCadFuncMouseClicked(evt);
            }
        });

        jlCadPaci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hms/images/BOTAO02.PNG"))); // NOI18N
        jlCadPaci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCadPaciMouseClicked(evt);
            }
        });

        jlCadEstru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hms/images/BOTAO03.PNG"))); // NOI18N

        jlCadMedi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hms/images/BOTAO04.PNG"))); // NOI18N
        jlCadMedi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCadMediMouseClicked(evt);
            }
        });

        jlPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hms/images/BOTAO05.PNG"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hms/images/botao09.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hms/images/botao 08.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hms/images/botao07.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hms/images/botao06.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jlCadFunc)
                        .addGap(18, 18, 18)
                        .addComponent(jlCadPaci)
                        .addGap(18, 18, 18)
                        .addComponent(jlCadEstru)
                        .addGap(18, 18, 18)
                        .addComponent(jlCadMedi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlPesq)
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlPesq)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(65, 65, 65)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlCadFunc)
                                    .addComponent(jlCadPaci)
                                    .addComponent(jlCadEstru)
                                    .addComponent(jlCadMedi))))
                        .addGap(316, 316, 316))))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hms/images/rodape.png"))); // NOI18N

        javax.swing.GroupLayout jdpAreaDeTrabalhoLayout = new javax.swing.GroupLayout(jdpAreaDeTrabalho);
        jdpAreaDeTrabalho.setLayout(jdpAreaDeTrabalhoLayout);
        jdpAreaDeTrabalhoLayout.setHorizontalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jdpAreaDeTrabalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2))
        );
        jdpAreaDeTrabalhoLayout.setVerticalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpAreaDeTrabalhoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jdpAreaDeTrabalho.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpAreaDeTrabalho.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpAreaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpAreaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){

        }
    }//GEN-LAST:event_jPanel1KeyPressed
 
    private void jlCadMediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCadMediMouseClicked
        GuiCadastroFuncionario oi = new GuiCadastroFuncionario();
        oi.setVisible(true);
    }//GEN-LAST:event_jlCadMediMouseClicked

    private void jlCadPaciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCadPaciMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               GuiCadastroPaciente cadPaci =  new GuiCadastroPaciente();
                jdpAreaDeTrabalho.add(cadPaci);
                cadPaci.setVisible(true);
            }
        });

    }//GEN-LAST:event_jlCadPaciMouseClicked

    mPessoa m = new mPessoa();
   
    private void jlCadFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCadFuncMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GuiCadastroFuncionario cadFunc = new GuiCadastroFuncionario();
                jdpAreaDeTrabalho.add(cadFunc);
                cadFunc.setVisible(true);
            }
        });
    }//GEN-LAST:event_jlCadFuncMouseClicked

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane jdpAreaDeTrabalho;
    private javax.swing.JLabel jlCadEstru;
    private javax.swing.JLabel jlCadFunc;
    private javax.swing.JLabel jlCadMedi;
    private javax.swing.JLabel jlCadPaci;
    private javax.swing.JLabel jlPesq;
    // End of variables declaration//GEN-END:variables
}
